### ISSUE TITLE
Current day in the popup should be more proeminent

### ISSUE THREAD

**Issue by lainsce** [elementary/wingpanel-indicator-datetime#90]
As it stands right now, it looks like this, which makes it easy to miss which day is the current one, at a glance:
![screenshot from 2018-08-20 13-19-43](https://user-images.githubusercontent.com/4886639/44352948-00231800-a47c-11e8-87c2-7caeb850685e.png)

I propose it has a subtle circle, using the theme's accent color, to emphasize the current day:
![e](https://user-images.githubusercontent.com/4886639/46514657-8f6e6a00-c835-11e8-9530-33bc15dedc3a.png)

To reach that circle, one may use this CSS:
```css
.accent {
    background-color: shade(@colorAccent, 1.55);
    color: shade(@colorAccent, 0.66);
}
```

EDIT: Made the mockup use a better color for current day that is at least WCAG AA compliant.
